### ISSUE TITLE
Conflict with SCSS?

### ISSUE THREAD

**Issue by billzhong** [fwojciec/simple-i18n-example#2]
Hi,

I try to use this i18n method with SCSS. I enabled SCSS support by following [official](https://github.com/zeit/next-plugins/tree/master/packages/next-sass) docs. However, after I add `import "../styles.scss"` to `/components/Layout.tsx`, the `/` to `/en` or any languages redirection won't work. The locale subpaths still works, just the redirect doesn't work.

**Comment by fwojciec** [comment]
Thanks for reporting this! Can you try the latest version? I hope the new, simplified version of the redirect logic in `pages/index.tsx` will solve the issue.

**Comment by billzhong** [comment]
Yes, it works, thanks. Also I tried ```router.replace(`/${getInitialLocale()}`);``` and it is working too. Just curious what caused this issue?

**Comment by fwojciec** [comment]
No idea, to be honest.  In my experience css/scss in next.js is very quirky, which is why I'm currently using `styled-jsx` in my projects -- maybe things will improve after [https://github.com/zeit/next.js/issues/8626](this) is added.

I'm currently without my laptop so I didn't have a chance to debug this thoroughly -- it did look like the router object returned by `useRouter` hook is different when the stylesheet is imported compared to a scenario where no scss imports are included...

I'll close this for now, but if you happen to find out more about this please feel free to re-open.  Thanks again!
