### ISSUE TITLE
JS implementation of this project

### ISSUE THREAD

**Issue by Malieh** [fwojciec/simple-i18n-example#8]
Thank you for this project.

I would love a javascript implementation of the project. I have been trying to transpile independent files from ts to js but I end up with errors and I don't want to migrate to ts since I am not familiar with it

**Comment by fwojciec** [comment]
Sorry, no time to work on this right now :(.  My suggestion would be to re-implement this in JS using the code as a guide rather than just using the code verbatim.  It's really quite a simple implementation, and would likely benefit from being adjusted for a particular project rather than using as is in either case.

**Comment by n12o** [comment]
There was a closed issue #3 that seems to implement this example in plain JS. 

[Fork is here](https://github.com/arzafran/simple-i18n-example/tree/js-version)

It seems to work for me. At least it is a good reference.

**Comment by alexllao** [comment]
Thnks a lot!

**Comment by alexllao** [comment]
I've tested JS implementation. All ok but pages/index.js blocks mi browser, instead if directly to the path / of everything works ok. Thnks 4 all!

**Comment by fwojciec** [comment]
Try the suggestion in this comment -- it might be what's causing the problem on the pages/index.js page.  https://github.com/fwojciec/simple-i18n-example/issues/12#issuecomment-621906484
